//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.1
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Login
{
    /// <summary>
    /// lblLoginMsg control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblLoginMsg;

    /// <summary>
    /// txtLoginName control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtLoginName;

    /// <summary>
    /// txtLoginEmail control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtLoginEmail;

    /// <summary>
    /// txtLoginPassword control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtLoginPassword;

    /// <summary>
    /// hdnRole control.
    /// </summary>
    protected global::System.Web.UI.WebControls.HiddenField hdnRole;

    /// <summary>
    /// btnLogin control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button btnLogin;
}
