//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceStudentSystem.Pages.Student
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblName;
        protected global::System.Web.UI.WebControls.GridView gvRecent;
    }
}
