//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceStudentSystem.Pages.Student
{
    public partial class MyApplications
    {
        protected global::System.Web.UI.WebControls.GridView gvApplications;
    }
}
