//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceStudentSystem.Pages.Student
{
    public partial class Portfolio
    {
        protected global::System.Web.UI.WebControls.Label lblMsg;
        protected global::System.Web.UI.WebControls.TextBox txtPortfolioTitle;
        protected global::System.Web.UI.WebControls.TextBox txtPortfolioDesc;
        protected global::System.Web.UI.WebControls.FileUpload fuPortfolio;
        protected global::System.Web.UI.WebControls.Button btnUpload;
        protected global::System.Web.UI.WebControls.GridView gvPortfolio;
    }
}
