//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceStudentSystem.Pages.Client
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.GridView gvMyProjects;
    }
}
