//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceStudentSystem.Pages.Admin
{
    public partial class Dashboard
    {
        protected global::System.Web.UI.WebControls.Label lblTotalUsers;
        protected global::System.Web.UI.WebControls.Label lblTotalProjects;
        protected global::System.Web.UI.WebControls.Label lblOpenProjects;
        protected global::System.Web.UI.WebControls.GridView gvUsers;
    }
}
