//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.1
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Register
{
    /// <summary>
    /// txtusername control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtusername;

    /// <summary>
    /// txtemail control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtemail;

    /// <summary>
    /// txtmbl control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtmbl;

    /// <summary>
    /// drpcity control.
    /// </summary>
    protected global::System.Web.UI.WebControls.DropDownList drpcity;

    /// <summary>
    /// txtaddress control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtaddress;

    /// <summary>
    /// rdogen control.
    /// </summary>
    protected global::System.Web.UI.WebControls.RadioButtonList rdogen;

    /// <summary>
    /// drprole control.
    /// </summary>
    protected global::System.Web.UI.WebControls.DropDownList drprole;

    /// <summary>
    /// imgupload control.
    /// </summary>
    protected global::System.Web.UI.WebControls.FileUpload imgupload;

    /// <summary>
    /// txtpassword control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtpassword;

    /// <summary>
    /// Save_btn control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button Save_btn;

    /// <summary>
    /// GridView1 control.
    /// </summary>
    protected global::System.Web.UI.WebControls.GridView GridView1;
}
