//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.1
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Web.UI;
using System.Web.UI.WebControls;

public partial class Contact
{
    /// <summary>
    /// lblMessage control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Label lblMessage;

    /// <summary>
    /// txtName control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtName;

    /// <summary>
    /// txtEmail control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtEmail;

    /// <summary>
    /// txtMessage control.
    /// </summary>
    protected global::System.Web.UI.WebControls.TextBox txtMessage;

    /// <summary>
    /// btnSubmit control.
    /// </summary>
    protected global::System.Web.UI.WebControls.Button btnSubmit;
}
