//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceStudentSystem.Pages.Account
{
    public partial class Login
    {
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.TextBox txtUsername;
        protected global::System.Web.UI.WebControls.TextBox txtPassword;
        protected global::System.Web.UI.WebControls.CheckBox chkRememberMe;
        protected global::System.Web.UI.WebControls.Button btnLogin;
    }
}
