//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreelanceStudentSystem
{
    public partial class Newsletter
    {
        protected global::System.Web.UI.WebControls.TextBox txtNewsletterEmail;
        protected global::System.Web.UI.WebControls.Button btnSubscribe;
        protected global::System.Web.UI.WebControls.Label lblStatus;
    }
}
