//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templet_Website
{
    public partial class Blog
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Repeater rptBlogPosts;

        protected global::System.Web.UI.WebControls.Panel pnlStaticPosts;

        protected global::System.Web.UI.WebControls.TextBox txtNewsletterEmail;

        protected global::System.Web.UI.WebControls.Button btnSubscribe;

        protected global::System.Web.UI.WebControls.Label lblSubscribeMsg;
    }
}
