//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templet_Website
{
    public partial class Service_Details
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
