//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Templet_Website
{
    public partial class Starter_Page
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
    }
}
